# import smtplib
#
# my_email = 'mallalikhitha9@gmail.com'
# password = "rkzdqfjnwgvwnflr"
#
# with smtplib.SMTP("smtp.gmail.com", 587) as connection:
#     # Secure - Start Transport layer security
#     connection.starttls()
#     connection.login(user=my_email, password=password)
#     connection.sendmail(
#         from_addr=my_email,
#         to_addrs='mramanaji@gmail.com',
#         msg='Subject:This is from Python!!\n\nThis is a mail generated by python.'
#     )

# import datetime as dt
#
# now = dt.datetime.now()
# print(now.year)
# print(type(now.year))
# print(now.day)
# print(now.month)
# # weekday starts from 0
# print(now.weekday())
# # isoweekday starts from 1
# print(now.isoweekday())
#
# my_bday = dt.datetime(year=2003, month=9, day=15, hour=12)
# print(my_bday)

# Every Monday Quotes

import datetime as dt
import random
import smtplib

with open('quotes.txt') as file:
    quotes = file.readlines()
rand_quote = random.choice(quotes)

now = dt.datetime.now()
weekday = now.weekday()
if weekday == 0:
    # print(rand_quote)
    my_email = 'mallalikhitha9@gmail.com'
    password = 'rkzdqfjnwgvwnflr'
    with smtplib.SMTP('smtp.gmail.com', 587) as connection:
        connection.starttls()
        connection.login(user=my_email, password=password)
        connection.sendmail(
            from_addr=my_email,
            to_addrs=my_email,
            msg=f'Subject:Monday Motivation\n\n{rand_quote}'
        )
